<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>JSDoc: Source: index.js</title>

    <script src="scripts/prettify/prettify.js"> </script>
    <script src="scripts/prettify/lang-css.js"> </script>
    <!--[if lt IE 9]>
      <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    <link type="text/css" rel="stylesheet" href="styles/prettify-tomorrow.css">
    <link type="text/css" rel="stylesheet" href="styles/jsdoc-default.css">
</head>

<body>

<div id="main">

    <h1 class="page-title">Source: index.js</h1>

    



    
    <section>
        <article>
            <pre class="prettyprint source linenums"><code>const { fakeApiCall } = require('./lib/http');

/**
 * calling multiple promises
 */
const allSettledTest = async () => {
  try {
    const t = await Promise.allSettled([fakeApiCall(1000), fakeApiCall(10)]);
    console.log(t);
  } catch (e) {
    console.error(e);
  }
};

/**
 * while loop w/ promises
 */
const whileLoopTest = async () => {
  let x = 0;
  while (x &lt; 5) {
    x++;
    await Promise.allSettled([fakeApiCall(1000), fakeApiCall(10)]);
  }
};

/**
 * catching error
 */
const catchErrorTest = () => {
  const p = Promise.reject('no');
  p.catch((e) => {
    console.error(e);
    throw e;
  }).catch(e => console.error(e));
};

/**
 * catch and throw
 * @returns {Promise&lt;void>}
 */
const catchErrorTest2 = async () => {
  const p = Promise.reject('no');
  try {
    await p;
  } catch (e) {
    console.error(e);
    throw e;
  }
};

/**
 * catch and throw and catch
 * @returns {Promise&lt;void>}
 */
const catchErrorTest3 = async () => {
  const p = Promise.reject('no');
  try {
    try {
      await p;
    } catch (e) {
      console.error(e);
      throw e;
    }
  } catch (e) {
    console.error(e);
  }
};

/**
 *
 * @returns {Promise&lt;void>}
 */
const promiseAllTest = async () => {
  try {
    const t = await Promise.all([Promise.reject('no'), Promise.resolve('yes')]);
    console.log(t);
  } catch (e) {
    console.error(e);
  }
};

/**
 *
 * @returns {Promise&lt;void>}
 */
const promiseAllSettledTest = async () => {
  try {
    const t = await Promise.allSettled([Promise.reject('no'), Promise.resolve('yes')]);
    console.log(t);
  } catch (e) {
    console.error(e);
  }
};
</code></pre>
        </article>
    </section>




</div>

<nav>
    <h2><a href="index.html">Home</a></h2><h3>Global</h3><ul><li><a href="global.html#allSettledTest">allSettledTest</a></li><li><a href="global.html#catchErrorTest">catchErrorTest</a></li><li><a href="global.html#catchErrorTest2">catchErrorTest2</a></li><li><a href="global.html#catchErrorTest3">catchErrorTest3</a></li><li><a href="global.html#fakeHandler">fakeHandler</a></li><li><a href="global.html#promiseAllSettledTest">promiseAllSettledTest</a></li><li><a href="global.html#promiseAllTest">promiseAllTest</a></li><li><a href="global.html#whileLoopTest">whileLoopTest</a></li></ul>
</nav>

<br class="clear">

<footer>
    Documentation generated by <a href="https://github.com/jsdoc/jsdoc">JSDoc 3.6.6</a> on Wed Mar 03 2021 09:53:25 GMT-0500 (Eastern Standard Time)
</footer>

<script> prettyPrint(); </script>
<script src="scripts/linenumber.js"> </script>
</body>
</html>
